server:
  port: 8086
spring:
  datasource:
    url: jdbc:mysql://192.168.31.112:3306/seven?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.four.model

  data:
    mongodb:
      uri: mongodb://192.168.116.129:27017/fff
  application:
    name: mongoweb



redis:
    #database:9
    host: 192.168.116.129
    port: 6379
    password: 123456
    database: 1
    pool:
      max-idle: 8
      min-idle: 0
      max-active: 8
      max-wait: -1
